# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fibonacci 
#' 
#' The Fibonacci Sequence is the series of numbers: 
#' 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ... 
#' The next number is found by adding up the two numbers before it.
#' 
#' @param n integer. Length of the Fibonacci Sequence
#' 
#' @details Implemented in C++
#' 
#' @return The Fibonacci Sequence
#' 
#' @export
#' 
fibonacci <- function(n) {
    .Call(`_sample_fibonacci`, n)
}

